SELECT
	TO_CHAR(LAST_DAY(a.WRITE_DATE),'YYYY/MM/DD') as LAST_DATE,
	a.NAME,
	a.BOARDING_DATE,
	a.DESTINATION,
	a.TYPE,
	a.DEPARTURE,
	a.ARROW,
	a.DESTINATION_STATION,
	a.MONEY,
	a.REMARKS,
	a.TRAIN,
	a.TAXI,
	a.BUS,
	a.TOTAL
FROM
	DUAL, TRANSPORTATION a
WHERE
	a.WRITE_DATE = (
		SELECT
			MAX(b.WRITE_DATE)
		FROM
			TRANSPORTATION b
	)