INSERT INTO TRANSPORTATION (
	WRITE_DATE,
	DEPARTMENT,
	NAME,
	BOARDING_DATE,
	DESTINATION,
	TYPE,
	DEPARTURE,
	ARROW,
	DESTINATION_STATION,
	MONEY,
	REMARKS,
	TRAIN,
	TAXI,
	BUS,
	TOTAL
)
VALUES (
	/*writeDate*/'2018/06/30',
	/*department*/'1課',
	/*name*/'小川',
	/*boardingDate*/'2018/06/15',
	/*destination*/'どこか',
	/*type*/'電車',
	/*departure*/'どこか',
	/*arrow*/'→',
	/*destinationStation*/'どこか',
	/*money*/'100',
	/*remarks*/'面談',
	/*train*/'100',
	/*taxi*/'0',
	/*bus*/'0',
	/*total*/'100'
);